import { useEffect, useState } from "react";
import { ImageBackground, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { ActionButton, Eyebrow, Panel, ProgressBar } from "@/components/nf-ui";
import { BrasswakeAtmosphere } from "@/components/brasswake-atmosphere";
import { demoStageAt, demoStages, nextDemoStage } from "@/lib/demo-mode";
import { pirateVisuals } from "@/lib/pirate-visuals";

export default function DemoScreen() {
  const router = useRouter() as unknown as { back: () => void; push: (route: string) => void };
  const [stageIndex, setStageIndex] = useState(0); const [playing, setPlaying] = useState(false);
  const stage = demoStageAt(stageIndex); const complete = stageIndex === demoStages.length - 1;
  const artwork = stage.id === "windup" || stage.id === "conductor" ? pirateVisuals.conductor : pirateVisuals.dockyards;
  useEffect(() => { if (!playing || complete) return; const timer = setTimeout(() => setStageIndex((current) => nextDemoStage(current)), stage.durationMs); return () => clearTimeout(timer); }, [playing, complete, stage.durationMs]);
  const restart = () => { setStageIndex(0); setPlaying(true); };
  const continueDemo = () => { if (complete) { restart(); return; } setPlaying(true); setStageIndex((current) => nextDemoStage(current)); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Eyebrow color="#C7973A">Guided demo // Auto + touch</Eyebrow><Text style={styles.title}>BLOODWAKE REPLAY</Text></View><Text style={styles.step}>{String(stageIndex + 1).padStart(2, "0")} / {String(demoStages.length).padStart(2, "0")}</Text></View>
	    <Panel style={{ ...styles.stage, borderLeftColor: stage.color }}><ImageBackground source={artwork} style={styles.stageArt} imageStyle={styles.stageArtImage}><View style={styles.artShade} /><BrasswakeAtmosphere compact /><Text style={[styles.artLabel, { color: stage.color }]}>{stage.id === "conductor" || stage.id === "windup" ? "THE CONDUCTOR OF THE DROWNED" : "BRASSWAKE HARBOR"}</Text></ImageBackground><Eyebrow color={stage.color}>{stage.eyebrow}</Eyebrow><Text style={styles.stageTitle}>{stage.title}</Text><Text style={styles.detail}>{stage.detail}</Text><View style={styles.metric}><Text style={styles.metricLabel}>{stage.metricLabel}</Text><Text style={[styles.metricValue, { color: stage.color }]}>{stage.metric}</Text></View><ProgressBar value={stage.progress} color={stage.color} /><Text style={styles.progressLabel}>DEMO PROGRESSION // {stage.progress}%</Text></Panel>
    <Panel><Eyebrow color="#B68A39">Playback controls</Eyebrow><Text style={styles.controlCopy}>{playing && !complete ? "The replay advances automatically. Pause to inspect a card, or step forward manually." : complete ? "The full local feature tour is complete. Restart it at any time." : "Begin the replay or step through it at your own pace."}</Text><View style={styles.controlRow}><ActionButton label={playing ? "PAUSE" : complete ? "REPLAY" : "PLAY DEMO"} detail={playing ? "HOLD THIS SCENE" : complete ? "RUN AGAIN" : "AUTOMATIC TOUR"} tone="violet" onPress={() => playing ? setPlaying(false) : complete ? restart() : setPlaying(true)} /><ActionButton label={complete ? "RESTART" : "NEXT SCENE"} detail={complete ? "RETURN TO OPENING" : "STEP FORWARD"} tone="ghost" onPress={continueDemo} /></View><ActionButton label="OPEN THIS FEATURE" detail="LEAVE THE REPLAY AT THIS FEATURE SCREEN" tone="cyan" onPress={() => router.push(stage.route)} /></Panel>
    <Panel><Eyebrow color="#A89D86">What this demo proves</Eyebrow><Text style={styles.boundary}>The replay is fully local and interactive: it can auto-advance, pause, restart, step between feature cards, and open each live prototype surface. It is a product tour, not a substitute for a signed Godot mobile export, live multiplayer session, store entitlement, or remote account service.</Text></Panel><ActionButton label="RETURN TO BLOODWAKE HARBOR" tone="ghost" onPress={() => router.back()} />
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 18, gap: 16 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, title: { color: "#EDE1C4", fontSize: 29, lineHeight: 34, fontWeight: "900", marginTop: -4 }, step: { color: "#C7973A", fontSize: 13, fontWeight: "900", letterSpacing: 0.8 }, stage: { borderLeftWidth: 3, gap: 10, minHeight: 310, justifyContent: "center" }, stageArt: { height: 124, borderRadius: 13, overflow: "hidden", justifyContent: "flex-end", borderWidth: 1, borderColor: "#70532B", backgroundColor: "#211A15" }, stageArtImage: { opacity: 0.82 }, artShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "#0806048C" }, artLabel: { padding: 11, fontSize: 10, fontWeight: "900", letterSpacing: 0.9 }, stageTitle: { color: "#EDE1C4", fontSize: 25, lineHeight: 31, fontWeight: "900" }, detail: { color: "#C8BBA1", fontSize: 13, lineHeight: 20 }, metric: { paddingTop: 4, gap: 3 }, metricLabel: { color: "#A89D86", fontSize: 9, fontWeight: "900", letterSpacing: 0.9 }, metricValue: { fontSize: 14, fontWeight: "900", letterSpacing: 0.4 }, progressLabel: { color: "#8C806B", fontSize: 9, fontWeight: "800", letterSpacing: 0.6 }, controlCopy: { color: "#B9AF9A", fontSize: 12, lineHeight: 18 }, controlRow: { flexDirection: "row", gap: 9 }, boundary: { color: "#A89D86", fontSize: 11, lineHeight: 17 } });
