import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { ActionButton, Eyebrow, Panel, ProgressBar } from "@/components/nf-ui";
import { blackoutBranch, blackoutProtocolBranches } from "@/lib/blackout-protocol";
import { useGame } from "@/lib/game-session";

export default function MissionTwoScreen() {
  const router = useRouter() as unknown as { back: () => void; push: (route: string) => void };
  const { missionTwoBranch, missionTwoStep, canStartStoryMission, chooseMissionTwoBranch, advanceMissionTwoStep } = useGame();
	if (!canStartStoryMission(2)) return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Eyebrow color="#82755F">Mission 02 // Locked</Eyebrow><Text style={styles.title}>THE BROKEN COMPASS</Text><Panel><Text style={styles.branchCopy}>Defeat Mission 01: Ashes Below before opening this branch. The campaign is locked in chronological order; checkpoints do not count as a completed mission.</Text></Panel><ActionButton label="RETURN TO CAMPAIGN" tone="ghost" onPress={() => router.back()} /></ScrollView></ScreenContainer>;
  const branch = blackoutBranch(missionTwoBranch);
  if (!branch) return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Eyebrow color="#8E5CFF">Mission 02 // Eclipse + 31 minutes</Eyebrow><Text style={styles.title}>BLACKOUT PROTOCOL</Text><Text style={styles.lead}>The first station is silent, but two emergency signals remain. The player can preserve the people caught above the gates or pursue the relay intelligence that may end the eclipse. This choice is stored locally and changes the next mission briefing.</Text><View style={styles.branchList}>{blackoutProtocolBranches.map((option) => <Panel key={option.id} style={{ ...styles.branchCard, borderLeftColor: option.color }}><Eyebrow color={option.color}>Branch directive</Eyebrow><Text style={styles.branchTitle}>{option.title}</Text><Text style={styles.branchCopy}>{option.directive}</Text><Text style={styles.risk}><Text style={styles.riskLabel}>RISK: </Text>{option.risk}</Text><Text style={styles.reward}><Text style={styles.riskLabel}>LEAD: </Text>{option.reward}</Text><ActionButton label={`CHOOSE ${option.title}`} detail="LOCAL PERSISTENT DECISION" tone={option.id === "last_platform" ? "violet" : "crimson"} onPress={() => chooseMissionTwoBranch(option.id)} /></Panel>)}</View><ActionButton label="RETURN TO CAMPAIGN" tone="ghost" onPress={() => router.back()} /></ScrollView></ScreenContainer>;
  const currentScene = branch.scenes[Math.min(missionTwoStep, branch.scenes.length - 1)];
  const complete = missionTwoStep >= branch.scenes.length;
  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Eyebrow color={branch.color}>Mission 02 // Branch committed</Eyebrow><Text style={styles.title}>{branch.title}</Text><Panel style={{ ...styles.progressPanel, borderLeftColor: branch.color }}><Eyebrow color={branch.color}>{complete ? "Branch outcome" : `Scene ${missionTwoStep + 1} of ${branch.scenes.length}`}</Eyebrow><Text style={styles.sceneTitle}>{complete ? "THE OBSERVATORY OPENS" : currentScene.title}</Text><Text style={styles.branchCopy}>{complete ? branch.outcome : currentScene.context}</Text>{!complete ? <><Text style={styles.objective}>OBJECTIVE // {currentScene.objective}</Text><ProgressBar value={Math.round((missionTwoStep / branch.scenes.length) * 100)} color={branch.color} /><ActionButton label="RESOLVE LOCAL SCENE" detail="SAVES THIS BRANCH" tone={branch.id === "last_platform" ? "violet" : "crimson"} onPress={advanceMissionTwoStep} /></> : <><ProgressBar value={100} color={branch.color} /><Text style={styles.complete}>BRANCH LEDGER SAVED LOCALLY</Text><ActionButton label="ENTER THE OBSERVATORY" detail="BRANCH-SPECIFIC CONVERGENCE" tone={branch.id === "last_platform" ? "violet" : "crimson"} onPress={() => router.push("/observatory")} /></>}</Panel><Panel><Eyebrow color="#A9A3B5">Decision record</Eyebrow><Text style={styles.sectionTitle}>Your next mission begins differently.</Text><Text style={styles.branchCopy}>This vertical slice retains the selected route and objective progress on this device. It does not yet export a Godot save file, synchronize across devices, or promise a networked campaign ledger.</Text></Panel><ActionButton label="RETURN TO CAMPAIGN" tone="ghost" onPress={() => router.back()} /></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 32, gap: 15 }, title: { color: "#F5F0E9", fontSize: 30, lineHeight: 35, fontWeight: "900", marginTop: -8 }, lead: { color: "#C8C0D2", fontSize: 13, lineHeight: 20 }, branchList: { gap: 14 }, branchCard: { borderLeftWidth: 3, gap: 8 }, branchTitle: { color: "#F5F0E9", fontSize: 21, lineHeight: 26, fontWeight: "900" }, branchCopy: { color: "#C8C0D2", fontSize: 12, lineHeight: 18 }, risk: { color: "#FFABBF", fontSize: 11, lineHeight: 16 }, reward: { color: "#A6F4F1", fontSize: 11, lineHeight: 16 }, riskLabel: { color: "#F5F0E9", fontWeight: "900" }, progressPanel: { borderLeftWidth: 3, gap: 10 }, sceneTitle: { color: "#F5F0E9", fontSize: 22, lineHeight: 28, fontWeight: "900" }, objective: { color: "#E7CB63", fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, complete: { color: "#A6F4F1", fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, sectionTitle: { color: "#F5F0E9", fontSize: 17, fontWeight: "900" } });
