import { ScrollView, StyleSheet, Text } from "react-native";
import { useRouter } from "expo-router";
import { View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { ActionButton, Eyebrow, Panel, ProgressBar } from "@/components/nf-ui";
import { observatoryRoute } from "@/lib/observatory-convergence";
import { observatoryReward } from "@/lib/observatory-rewards";
import { useGame } from "@/lib/game-session";

export default function ObservatoryScreen() {
  const router = useRouter() as unknown as { back: () => void };
  const { missionTwoBranch, observatoryStep, canStartStoryMission, advanceObservatoryStep } = useGame();
  const route = observatoryRoute(missionTwoBranch);
  if (!route || !canStartStoryMission(3)) return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><Eyebrow color="#D93056">Mission 03 // Locked</Eyebrow><Text style={styles.title}>THE OBSERVATORY</Text><Panel><Text style={styles.copy}>Defeat Mission 02: The Broken Compass first. The Observatory will not open from a checkpoint, a partial branch, or an absent earlier campaign decision.</Text></Panel><ActionButton label="RETURN TO CAMPAIGN" tone="ghost" onPress={() => router.back()} /></ScrollView></ScreenContainer>;
	const complete = observatoryStep >= route.scenes.length;
	const scene = route.scenes[Math.min(observatoryStep, route.scenes.length - 1)];
	const reward = observatoryReward(missionTwoBranch);
	const conductorVitality = [360, 270, 135, 0][Math.min(observatoryStep, route.scenes.length)];
	const conductorPhase = conductorVitality <= 0 ? "CORE SILENCED" : conductorVitality > 240 ? "PHASE 1 // SIGNAL BARRIER" : conductorVitality > 110 ? "PHASE 2 // LATTICE BREACH" : "PHASE 3 // ECLIPSE REVERSAL";
	return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Eyebrow color={route.color}>Mission 03 // Branch convergence</Eyebrow><Text style={styles.title}>THE OBSERVATORY</Text><Panel style={{ ...styles.boss, borderLeftColor: route.color }}><Eyebrow color="#E7CB63">The Conductor // Local status</Eyebrow><View style={styles.bossHeader}><Text style={styles.bossTitle}>OBSERVATORY CONDUCTOR</Text><Text style={[styles.bossValue, { color: route.color }]}>{conductorVitality} / 360</Text></View><Text style={styles.bossPhase}>{conductorPhase}</Text><ProgressBar value={Math.round((conductorVitality / 360) * 100)} color={conductorVitality > 0 ? route.color : "#E7CB63"} /><Text style={styles.bossCopy}>This status panel reconstructs the boss state from the device-local mission ledger. A future signed bridge may surface the live native encounter, but no cross-runtime telemetry is enabled in this prototype.</Text></Panel><Panel style={{ ...styles.origin, borderLeftColor: route.color }}><Eyebrow color={route.color}>Your route into the eclipse</Eyebrow><Text style={styles.copy}>{route.origin}</Text><Text style={styles.advantage}>{route.advantage}</Text></Panel><Panel style={{ ...styles.scene, borderLeftColor: route.color }}><Eyebrow color={route.color}>{complete ? "Convergence secured" : `Operation ${observatoryStep + 1} of ${route.scenes.length}`}</Eyebrow><Text style={styles.sceneTitle}>{complete ? "THE CORE BECOMES VISIBLE" : scene.title}</Text><Text style={styles.copy}>{complete ? route.resolution : scene.context}</Text>{!complete ? <><Text style={styles.objective}>OBJECTIVE // {scene.objective}</Text><ProgressBar value={Math.round((observatoryStep / route.scenes.length) * 100)} color={route.color} /><ActionButton label="RESOLVE OBSERVATORY OPERATION" detail="SAVES LOCAL CONVERGENCE" tone={route.branch === "last_platform" ? "violet" : "crimson"} onPress={advanceObservatoryStep} /></> : <><ProgressBar value={100} color={route.color} /><Text style={styles.complete}>OBSERVATORY LEDGER SAVED LOCALLY</Text></>}</Panel>{complete && reward ? <Panel style={{ ...styles.reward, borderLeftColor: reward.color }}><Eyebrow color={reward.color}>Local completion reward</Eyebrow><Text style={styles.rewardTitle}>{reward.title}</Text><Text style={styles.objective}>{reward.cosmetic} // {reward.mechanic}</Text><Text style={styles.copy}>{reward.detail}</Text></Panel> : null}<Panel><Eyebrow color="#A9A3B5">Convergence boundary</Eyebrow><Text style={styles.copy}>Both routes converge on the same Observatory floor while preserving their distinct entry narration and tactical context. This mobile vertical slice stores the outcome only on this device and does not create a live campaign service.</Text></Panel><ActionButton label="RETURN TO CAMPAIGN" tone="ghost" onPress={() => router.back()} /></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 32, gap: 15 }, title: { color: "#F5F0E9", fontSize: 30, lineHeight: 35, fontWeight: "900", marginTop: -8 }, boss: { borderLeftWidth: 3, gap: 7 }, bossHeader: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", gap: 12 }, bossTitle: { color: "#F5F0E9", fontSize: 15, fontWeight: "900" }, bossValue: { fontSize: 12, fontWeight: "900" }, bossPhase: { color: "#E7CB63", fontSize: 10, fontWeight: "900", letterSpacing: 0.6 }, bossCopy: { color: "#82788F", fontSize: 10, lineHeight: 15 }, origin: { borderLeftWidth: 3, gap: 8 }, scene: { borderLeftWidth: 3, gap: 10 }, reward: { borderLeftWidth: 3, gap: 7 }, sceneTitle: { color: "#F5F0E9", fontSize: 23, lineHeight: 29, fontWeight: "900" }, rewardTitle: { color: "#F5F0E9", fontSize: 19, fontWeight: "900" }, copy: { color: "#C8C0D2", fontSize: 13, lineHeight: 20 }, advantage: { color: "#E7CB63", fontSize: 10, lineHeight: 16, fontWeight: "900", letterSpacing: 0.5 }, objective: { color: "#E7CB63", fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, complete: { color: "#A6F4F1", fontSize: 10, fontWeight: "900", letterSpacing: 0.7 } });
