import { ReactNode } from "react";
import { Pressable, StyleSheet, Text, View, type ViewStyle } from "react-native";
import { haptic } from "@/lib/haptics";
export function Panel({ children, style }: { children: ReactNode; style?: ViewStyle }) { return <View style={[styles.panel, style]}>{children}</View>; }
export function Eyebrow({ children, color = "#8E5CFF" }: { children: ReactNode; color?: string }) { return <Text style={[styles.eyebrow, { color }]}>{children}</Text>; }
export function ProgressBar({ value, color = "#3DE6E6" }: { value: number; color?: string }) { return <View style={styles.track}><View style={[styles.fill, { width: `${Math.max(0, Math.min(value, 100))}%`, backgroundColor: color }]} /></View>; }
export function ActionButton({ label, detail, tone = "violet", onPress, disabled = false, compact = false }: { label: string; detail?: string; tone?: "violet" | "crimson" | "cyan" | "ghost"; onPress: () => void; disabled?: boolean; compact?: boolean }) {
  const palette = { violet: { bg: "#B68A39", text: "#120D08" }, crimson: { bg: "#7A2130", text: "#F6E8CF" }, cyan: { bg: "#3D6F69", text: "#F6E8CF" }, ghost: { bg: "#211A15", text: "#EDE1C4" } }[tone];
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={() => { if (!disabled) haptic.light(); onPress(); }} style={({ pressed }) => [styles.button, compact && styles.buttonCompact, { backgroundColor: palette.bg, opacity: disabled ? 0.45 : pressed ? 0.82 : 1 }]}><Text style={[styles.buttonLabel, { color: palette.text }]}>{label}</Text>{detail ? <Text style={[styles.buttonDetail, { color: palette.text }]}>{detail}</Text> : null}</Pressable>;
}
export function Pill({ label, active = false, color = "#8E5CFF", onPress }: { label: string; active?: boolean; color?: string; onPress?: () => void }) {
  const content = <Text style={[styles.pillText, { color: active ? "#08070C" : "#CFC8DA" }]}>{label}</Text>;
  if (!onPress) return <View style={[styles.pill, active && { backgroundColor: color, borderColor: color }]}>{content}</View>;
  return <Pressable accessibilityRole="button" onPress={() => { haptic.selection(); onPress(); }} style={({ pressed }) => [styles.pill, active && { backgroundColor: color, borderColor: color }, pressed && { opacity: 0.72 }]}>{content}</Pressable>;
}
const styles = StyleSheet.create({ panel: { backgroundColor: "#1A1510", borderRadius: 20, borderWidth: 1, borderColor: "#4C3924", padding: 16, gap: 10, shadowColor: "#000000", shadowOpacity: 0.3, shadowRadius: 9, shadowOffset: { width: 0, height: 4 } }, eyebrow: { fontSize: 11, lineHeight: 15, fontWeight: "800", letterSpacing: 1.6, textTransform: "uppercase" }, track: { height: 7, borderRadius: 20, backgroundColor: "#33281C", overflow: "hidden", flex: 1 }, fill: { height: "100%", borderRadius: 20 }, button: { minHeight: 54, paddingHorizontal: 17, paddingVertical: 10, borderRadius: 16, justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "#D0A45066" }, buttonCompact: { minHeight: 42, paddingVertical: 7, borderRadius: 13 }, buttonLabel: { fontSize: 14, lineHeight: 19, fontWeight: "900", letterSpacing: 0.5, textAlign: "center" }, buttonDetail: { marginTop: 2, fontSize: 10, lineHeight: 14, fontWeight: "700", opacity: 0.74, textAlign: "center" }, pill: { minHeight: 34, justifyContent: "center", alignItems: "center", paddingHorizontal: 12, borderRadius: 999, borderWidth: 1, borderColor: "#644D2C", backgroundColor: "#211A15" }, pillText: { fontSize: 11, fontWeight: "800", letterSpacing: 0.3 } });
