import { Animated, Pressable, StyleSheet, Text, View } from "react-native";
import { useEffect, useRef } from "react";

import { ActionButton, Eyebrow } from "@/components/nf-ui";

const tutorialSteps = [
  { eyebrow: "Tactical briefing // 01", title: "COMMAND THE DECK", copy: "The primary deployment dock begins Mission 01. Story missions remain locked in first-to-last order until the current chapter is defeated.", accent: "#C7973A", action: "NEXT // VIEW COMMAND RAIL" },
  { eyebrow: "Tactical briefing // 02", title: "READ THE COMMAND RAIL", copy: "Deploy, Modes, Story, Loadout, and Captain are always one tap away. The rail stays horizontal for two-thumb landscape play.", accent: "#4A877A", action: "NEXT // REVIEW TACTICAL INTEL" },
  { eyebrow: "Tactical briefing // 03", title: "CHOOSE YOUR ROUTE", copy: "Use the graphical slice for native Godot combat, Blood Hunt for local drills, and the Story map to track campaign clearance. No network session is created.", accent: "#8D2634", action: "ENTER COMMAND" },
] as const;

export function TacticalTutorialOverlay({ step, onAdvance, onDismiss }: { step: number; onAdvance: () => void; onDismiss: () => void }) {
  const current = tutorialSteps[Math.max(0, Math.min(step, tutorialSteps.length - 1))];
  const opacity = useRef(new Animated.Value(0)).current;
  const rise = useRef(new Animated.Value(20)).current;
  useEffect(() => { opacity.setValue(0); rise.setValue(20); Animated.parallel([Animated.timing(opacity, { toValue: 1, duration: 220, useNativeDriver: true }), Animated.timing(rise, { toValue: 0, duration: 260, useNativeDriver: true })]).start(); }, [current, opacity, rise]);
  return <View style={styles.overlay}><View style={[styles.axis, { backgroundColor: current.accent }]} /><View style={[styles.ring, { borderColor: current.accent }]} /><Animated.View style={[styles.card, { opacity, transform: [{ translateY: rise }] }]}><View style={styles.cardHeader}><Eyebrow color={current.accent}>{current.eyebrow}</Eyebrow><Text style={styles.stepCount}>{String(step + 1).padStart(2, "0")} / 03</Text></View><Text style={styles.title}>{current.title}</Text><Text style={styles.copy}>{current.copy}</Text><View style={[styles.callout, { borderLeftColor: current.accent }]}><Text style={styles.calloutLabel}>LANDSCAPE CONTROL NOTE</Text><Text style={styles.calloutCopy}>This briefing is device-local. Dismiss it once and it will not block the command deck again.</Text></View><ActionButton label={current.action} detail="CONTINUE LOCAL BRIEFING" tone={step === tutorialSteps.length - 1 ? "crimson" : "cyan"} onPress={onAdvance} /><Pressable accessibilityRole="button" onPress={onDismiss} style={({ pressed }) => [styles.skip, pressed && styles.pressed]}><Text style={styles.skipText}>SKIP BRIEFING</Text></Pressable></Animated.View></View>;
}

const styles = StyleSheet.create({ overlay: { position: "absolute", zIndex: 50, top: 0, right: 0, bottom: 0, left: 0, justifyContent: "center", alignItems: "center", padding: 24, backgroundColor: "#080604E8", overflow: "hidden" }, axis: { position: "absolute", left: "16%", top: 0, bottom: 0, width: 2, opacity: 0.8 }, ring: { position: "absolute", width: 500, height: 500, borderRadius: 250, borderWidth: 38, right: -190, top: -220, opacity: 0.28 }, card: { width: "100%", maxWidth: 630, gap: 11, padding: 22, borderWidth: 1, borderColor: "#665036", borderRadius: 18, backgroundColor: "#15100CEE" }, cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, stepCount: { color: "#A89D86", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: "#F6E8CF", fontSize: 28, lineHeight: 33, fontWeight: "900", letterSpacing: 0.6 }, copy: { color: "#D6C8B1", fontSize: 13, lineHeight: 19 }, callout: { gap: 3, borderLeftWidth: 3, paddingLeft: 10, paddingVertical: 2 }, calloutLabel: { color: "#A89D86", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 }, calloutCopy: { color: "#EDE1C4", fontSize: 11, lineHeight: 16 }, skip: { alignSelf: "center", paddingHorizontal: 12, paddingVertical: 5 }, skipText: { color: "#A89D86", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, pressed: { opacity: 0.68 } });
