export type HunterId = "duskstalker" | "crimson-vanguard" | "graveweaver" | "lumenfallen" | "cinder-surgeon" | "iron-revenant";
export type Difficulty = "Initiate" | "Nightmare" | "Eclipse";
export type MatchIntent = "blood_hunt" | "campaign";

export type Hunter = { id: HunterId; name: string; role: string; initials: string; accent: string; passive: string; tactical: string; movement: string; ultimate: string; counterplay: string; primaryWeapon: string; secondaryWeapon: string; fightingStyle: string; fpsCallsign: string };
export type Weapon = { name: string; class: string; cadence: string; note: string; owner: HunterId; slot: "PRIMARY" | "SECONDARY" };

export const hunters: Hunter[] = [
  { id: "duskstalker", name: "Bloodwake Captain", role: "Vampire cutlass duelist", initials: "BC", accent: "#B68A39", primaryWeapon: "Brasswake Wheel-Lock", secondaryWeapon: "Bloodwake Cutlass", fightingStyle: "Mobile pistol duels, close-range ripostes, and mist-assisted boarding pressure.", fpsCallsign: "DUELIST", passive: "Close-range eliminations briefly restore vitality.", tactical: "Mistwake — vanish through sea fog with a readable ripple.", movement: "Rigging Leap — a sharp targeted deck-to-deck dash.", ultimate: "Black Tide — darkens a dockside zone and reveals footsteps.", counterplay: "Sun-lantern damage disrupts the veil." },
  { id: "crimson-vanguard", name: "Red Marauder", role: "Blood-armored boarder", initials: "RM", accent: "#8D2634", primaryWeapon: "Catacomb Blunderbuss", secondaryWeapon: "Galleon Repeater", fightingStyle: "Point-blank breaching with a deliberate scatter blast and suppressive deck-lane follow-up.", fpsCallsign: "BREACHER", passive: "Sustained damage produces temporary resilience.", tactical: "Blood Bulwark — a directional crimson deck shield.", movement: "Boarding Charge — a knockback rush.", ultimate: "Keelbreaker — melee frenzy with recovery on elimination.", counterplay: "Vulnerable to flanks and ability baiting." },
  { id: "graveweaver", name: "Tide Hexer", role: "Cursed-water controller", initials: "TH", accent: "#4A877A", primaryWeapon: "Ossuary Censer Carbine", secondaryWeapon: "Saltbone Sickle", fightingStyle: "Measured curse bolts, area denial, and curved sickle executions around trapped routes.", fpsCallsign: "HEXER", passive: "Fresh blood trails stay visible to the hunter.", tactical: "Bone Net — a breakable slow and mark trap.", movement: "Salt Mist — quick movement while weapons are sheathed.", ultimate: "Drowned Chapel — spectral walls and temporary shades.", counterplay: "Traps and walls can be destroyed." },
  { id: "lumenfallen", name: "Brass Corsair", role: "Clockwork sharpshooter", initials: "CS", accent: "#C7973A", primaryWeapon: "Astral Harpoon", secondaryWeapon: "Sunspike Rapier", fightingStyle: "Deliberate long-lane harpoon shots followed by fast precision rapier recovery at close range.", fpsCallsign: "MARKSMAN", passive: "Precision hits build Eclipse Charge.", tactical: "Helios Brand — marks a target for self-only focus damage.", movement: "Sailburst — a directional aerial launch.", ultimate: "Eclipse Harpoon — a visible charged beam.", counterplay: "Requires line of sight and a readable charge-up." },
  { id: "cinder-surgeon", name: "Cinder Surgeon", role: "Ember-blood combat medic", initials: "CS", accent: "#D96A3A", primaryWeapon: "Ember-Leech Injector", secondaryWeapon: "Butcher’s Saw", fightingStyle: "Sustained incendiary needles, self-recovery windows, and brutal saw-tooth counterattacks.", fpsCallsign: "SURGEON", passive: "Burning targets return a small, capped vitality pulse on defeat.", tactical: "Coagulate — cauterize a short cone and slow burning threats.", movement: "Ash Slide — a low, fast reposition through smoke.", ultimate: "Red Remedy — a brief overheal ward with a visible ember halo.", counterplay: "Pressure the Surgeon outside short recovery range." },
  { id: "iron-revenant", name: "Iron Revenant", role: "Anchor-armored siege raider", initials: "IR", accent: "#6D8A94", primaryWeapon: "Leviathan Deck Cannon", secondaryWeapon: "Anchor Chain Gauntlet", fightingStyle: "Slow, crushing cannon volleys and chain-assisted crowd disruption from a resilient front line.", fpsCallsign: "SIEGE", passive: "Taking a hit grants a brief, visible poise window rather than extra damage.", tactical: "Anchor Snare — a breakable chain pull that controls one route.", movement: "Ballast Step — a short armored advance that resists knockback.", ultimate: "Tidebreaker Salvo — a telegraphed deck-cannon burst across a narrow lane.", counterplay: "Slow recovery and clear windups leave the Revenant vulnerable to flanks." },
];

export const weapons: Weapon[] = [
  { name: "Brasswake Wheel-Lock", class: "Burst sidearm", cadence: "3-round burst", note: "Accurate, reliable deck-lane pressure.", owner: "duskstalker", slot: "PRIMARY" },
  { name: "Bloodwake Cutlass", class: "Melee riposte", cadence: "Lunge", note: "Fast boarding-range counterpressure.", owner: "duskstalker", slot: "SECONDARY" },
  { name: "Catacomb Blunderbuss", class: "Scatter weapon", cadence: "Measured", note: "High-impact breach tool at boarding range.", owner: "crimson-vanguard", slot: "PRIMARY" },
  { name: "Galleon Repeater", class: "Close automatic", cadence: "Rapid", note: "Suppresses narrow deck corridors after a breach.", owner: "crimson-vanguard", slot: "SECONDARY" },
  { name: "Ossuary Censer Carbine", class: "Hex carbine", cadence: "Three pulse", note: "Cursed brass vapour marks a controlled firing lane.", owner: "graveweaver", slot: "PRIMARY" },
  { name: "Saltbone Sickle", class: "Hooked melee", cadence: "Arc slash", note: "Curves around trapped routes with readable reach.", owner: "graveweaver", slot: "SECONDARY" },
  { name: "Astral Harpoon", class: "Precision launcher", cadence: "Semi-auto", note: "Rewards deliberate first-person aim alignment.", owner: "lumenfallen", slot: "PRIMARY" },
  { name: "Sunspike Rapier", class: "Precision melee", cadence: "Thrust", note: "A quick close-range escape tool after a missed harpoon.", owner: "lumenfallen", slot: "SECONDARY" },
  { name: "Ember-Leech Injector", class: "Incendiary injector", cadence: "Burst stream", note: "Applies visible cinder pressure at short-to-mid range.", owner: "cinder-surgeon", slot: "PRIMARY" },
  { name: "Butcher’s Saw", class: "Saw melee", cadence: "Sawback", note: "Heavy close-pressure tool with a deliberate recovery.", owner: "cinder-surgeon", slot: "SECONDARY" },
  { name: "Leviathan Deck Cannon", class: "Siege cannon", cadence: "Heavy single", note: "Slow, forceful cannon shot with an obvious windup.", owner: "iron-revenant", slot: "PRIMARY" },
  { name: "Anchor Chain Gauntlet", class: "Chain melee", cadence: "Hook pull", note: "Controls a narrow boarding lane at close range.", owner: "iron-revenant", slot: "SECONDARY" },
];
export const arenas = ["Brasswake Dockyards", "Drowned Cathedral", "Eclipse Galleonworks"] as const;
export const difficultyConfig: Record<Difficulty, { target: number; enemyHit: number; label: string }> = { Initiate: { target: 5, enemyHit: 5, label: "Measured pressure" }, Nightmare: { target: 7, enemyHit: 8, label: "Aggressive pursuit" }, Eclipse: { target: 9, enemyHit: 11, label: "Relentless eclipse" } };
export function hunterFor(id: HunterId) { return hunters.find((hunter) => hunter.id === id) ?? hunters[0]; }
export function weaponsForHunter(id: HunterId) { return weapons.filter((weapon) => weapon.owner === id); }
