import type { Weapon } from "@/lib/game-data";

export type CombatStat = { label: string; value: number; fieldNote: string };
export type WeaponTelemetry = { accent: string; profile: string; stats: CombatStat[] };

const telemetry: Record<Weapon["name"], WeaponTelemetry> = {
	"Brasswake Wheel-Lock": { accent: "#C7973A", profile: "BALANCED DUELIST PROFILE", stats: [{ label: "HANDLING", value: 78, fieldNote: "A quick-ready profile for sidearm transitions and controlled bursts." }, { label: "REACH", value: 58, fieldNote: "Designed for deck lanes, not distant rigging shots." }, { label: "IMPACT", value: 61, fieldNote: "Reliable three-round pressure with no hidden damage bonus." }] },
	"Bloodwake Cutlass": { accent: "#D93056", profile: "CLOSE-PRESSURE PROFILE", stats: [{ label: "HANDLING", value: 92, fieldNote: "Fast ready time supports the Captain’s readable cutlass transition." }, { label: "REACH", value: 16, fieldNote: "This is a boarding-range tool with intentionally limited distance." }, { label: "MOBILITY", value: 83, fieldNote: "Lunge-oriented presentation supports close pressure without stat boosts." }] },
	"Catacomb Blunderbuss": { accent: "#8D2634", profile: "BOARDING IMPACT PROFILE", stats: [{ label: "HANDLING", value: 49, fieldNote: "A slower reset keeps its boarding impact readable and measured." }, { label: "REACH", value: 28, fieldNote: "Built for close quarters rather than long dockyard lanes." }, { label: "IMPACT", value: 94, fieldNote: "High point-blank presentation impact; it does not unlock paid power." }] },
	"Galleon Repeater": { accent: "#B24745", profile: "CORRIDOR SUPPRESSION PROFILE", stats: [{ label: "HANDLING", value: 72, fieldNote: "Stable recoil rhythm supports movement through tight deck routes." }, { label: "REACH", value: 44, fieldNote: "Its effective presentation band stays close to the boarding line." }, { label: "TEMPO", value: 88, fieldNote: "Fast automatic cadence trades deliberate precision for pressure." }] },
	"Ossuary Censer Carbine": { accent: "#4A877A", profile: "CURSE-LANE PROFILE", stats: [{ label: "HANDLING", value: 68, fieldNote: "A three-pulse rhythm gives route-control timing a clear cadence." }, { label: "REACH", value: 63, fieldNote: "Censer vapour is authored for deliberate mid-lane pressure." }, { label: "CONTROL", value: 84, fieldNote: "The Hexer profile emphasizes readable lane denial rather than damage spikes." }] },
	"Saltbone Sickle": { accent: "#70B6A6", profile: "HOOKED ARC PROFILE", stats: [{ label: "HANDLING", value: 74, fieldNote: "The hooked blade rewards timing around a corner or trap edge." }, { label: "REACH", value: 22, fieldNote: "Built for a close arc, not a ranged projectile." }, { label: "MOBILITY", value: 78, fieldNote: "Its recovery stays quick enough for a route-control exit." }] },
	"Astral Harpoon": { accent: "#E7CB63", profile: "PRECISION ANCHOR PROFILE", stats: [{ label: "HANDLING", value: 57, fieldNote: "Requires deliberate aim alignment before a shot is committed." }, { label: "REACH", value: 91, fieldNote: "The strongest line-of-sight profile in the local weapon dossier." }, { label: "IMPACT", value: 76, fieldNote: "A focused single-shot presentation profile rewards patience." }] },
	"Sunspike Rapier": { accent: "#F0D889", profile: "RAPIER RECOVERY PROFILE", stats: [{ label: "HANDLING", value: 88, fieldNote: "A quick thrust gives the marksman a precise exit after pressure closes in." }, { label: "REACH", value: 19, fieldNote: "The rapier is deliberately limited to boarding range." }, { label: "PRECISION", value: 85, fieldNote: "The weapon rewards a committed first-person line rather than wide swing coverage." }] },
	"Ember-Leech Injector": { accent: "#D96A3A", profile: "CINDER PRESSURE PROFILE", stats: [{ label: "HANDLING", value: 70, fieldNote: "Controlled injector bursts maintain a clear recovery rhythm." }, { label: "REACH", value: 53, fieldNote: "Cinder pressure works at short-to-mid distance." }, { label: "TEMPO", value: 76, fieldNote: "A burst stream gives the Surgeon sustained local pressure." }] },
	"Butcher’s Saw": { accent: "#E8955B", profile: "SAWBACK PROFILE", stats: [{ label: "HANDLING", value: 56, fieldNote: "The heavy saw is committed once it starts, making its recovery readable." }, { label: "REACH", value: 18, fieldNote: "Designed for dangerous close counters only." }, { label: "IMPACT", value: 87, fieldNote: "High authored impact is balanced by a clear recovery window." }] },
	"Leviathan Deck Cannon": { accent: "#6D8A94", profile: "SIEGE VOLLEY PROFILE", stats: [{ label: "HANDLING", value: 38, fieldNote: "The cannon’s slow ready time signals a strong commitment." }, { label: "REACH", value: 79, fieldNote: "A heavy shot claims a long but readable firing lane." }, { label: "IMPACT", value: 93, fieldNote: "Its force is paired with the roster’s slowest reload rhythm." }] },
	"Anchor Chain Gauntlet": { accent: "#9CB7C1", profile: "ANCHOR CONTROL PROFILE", stats: [{ label: "HANDLING", value: 51, fieldNote: "Chain handling remains deliberately measured." }, { label: "REACH", value: 37, fieldNote: "A narrow hook line can control one nearby boarding route." }, { label: "CONTROL", value: 89, fieldNote: "Lane control is its role, with clear setup and release windows." }] },
};

export function weaponTelemetryFor(name: Weapon["name"]): WeaponTelemetry {
  return telemetry[name];
}
