import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { ActionButton, Eyebrow, Panel, Pill } from "@/components/nf-ui";
import { CombatArena, type CombatResult } from "@/components/combat-arena";
import { AshesBelowMission } from "@/components/ashes-below-mission";
import { arenas, difficultyConfig, hunters, hunterFor, weaponsForHunter, type Difficulty } from "@/lib/game-data";
import { useGame } from "@/lib/game-session";
type ViewState = "setup" | "combat" | "debrief";
export default function HuntScreen() {
  const { selectedHunter, setSelectedHunter, selectedArena, setSelectedArena, difficulty, setDifficulty, matchIntent, prepareMatch, recordCompletion, recordStoryMissionDefeat, missionCheckpoint, saveMissionCheckpoint } = useGame(); const [state, setState] = useState<ViewState>("setup"); const [runId, setRunId] = useState(0); const [result, setResult] = useState<CombatResult | null>(null); const campaign = matchIntent === "campaign"; const hunter = hunterFor(selectedHunter); const start = () => { setRunId((id) => id + 1); setResult(null); setState("combat"); }; const end = (outcome: CombatResult) => { setResult(outcome); if (outcome.won) { recordCompletion(); if (campaign) recordStoryMissionDefeat(1); } setState("debrief"); };
  if (state === "combat") return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="p-0">{campaign ? <AshesBelowMission hunterId={selectedHunter} difficulty={difficulty} startingCheckpoint={missionCheckpoint} runId={runId} onEnd={end} onCheckpoint={saveMissionCheckpoint} onExit={() => setState("setup")} /> : <CombatArena hunterId={selectedHunter} difficulty={difficulty} campaign={false} runId={runId} onEnd={end} onExit={() => setState("setup")} />}</ScreenContainer>;
  if (state === "debrief" && result) return <Debrief result={result} hunterName={hunter.name} onRematch={start} onChange={() => { prepareMatch("blood_hunt"); setState("setup"); }} />;
  const loadout = weaponsForHunter(selectedHunter); return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Eyebrow color={campaign ? "#D93056" : "#3DE6E6"}>{campaign ? "The First Eclipse // Mission 01" : "Blood Hunt // Offline"}</Eyebrow><Text style={styles.title}>{campaign ? "ASHES BELOW" : "CHOOSE YOUR HUNT"}</Text><Text style={styles.lead}>{campaign ? "Move through a simulation of the maintenance district and break the eclipse-bound threats before the station seals." : "Configure a local target encounter. This is not an online lobby and does not award competitive progression."}</Text><Panel><Eyebrow color="#8E5CFF">Bloodline</Eyebrow><Text style={styles.sectionTitle}>Choose one of six first-person classes</Text><View style={styles.hunterGrid}>{hunters.map((item) => <Pill key={item.id} label={item.fpsCallsign} active={selectedHunter === item.id} color={item.accent} onPress={() => setSelectedHunter(item.id)} />)}</View><View style={[styles.dossier, { borderLeftColor: hunter.accent }]}><Text style={styles.dossierTitle}>{hunter.name} // {hunter.fpsCallsign}</Text><Text style={styles.dossierRole}>{hunter.role}</Text><Text style={styles.dossierCopy}>{hunter.fightingStyle}</Text><Text style={[styles.loadout, { color: hunter.accent }]}>LOADOUT // {loadout.map((weapon) => weapon.name.toUpperCase()).join(" + ")}</Text><Text style={styles.dossierCopy}>{hunter.tactical}</Text></View></Panel><Panel><Eyebrow color="#3DE6E6">Arena signal</Eyebrow><View style={styles.optionWrap}>{arenas.map((arena) => <Pill key={arena} label={arena.replace(" of ", " ")} active={selectedArena === arena} color="#3DE6E6" onPress={() => setSelectedArena(arena)} />)}</View></Panel><Panel><Eyebrow color="#E7CB63">Pressure level</Eyebrow><View style={styles.optionWrap}>{(Object.keys(difficultyConfig) as Difficulty[]).map((item) => <Pill key={item} label={item} active={difficulty === item} color="#E7CB63" onPress={() => setDifficulty(item)} />)}</View><Text style={styles.detail}>{difficultyConfig[difficulty].label} · {difficultyConfig[difficulty].target} local targets</Text></Panel><ActionButton label={campaign ? "BEGIN ASHES BELOW" : "START LOCAL HUNT"} detail={campaign ? "MISSION SIMULATION" : "NO NETWORK SESSION"} tone={campaign ? "crimson" : "violet"} onPress={start} /></ScrollView></ScreenContainer>;
}
function Debrief({ result, hunterName, onRematch, onChange }: { result: CombatResult; hunterName: string; onRematch: () => void; onChange: () => void }) { return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.debrief} showsVerticalScrollIndicator={false}><View style={[styles.resultSigil, { borderColor: result.won ? "#3DE6E6" : "#D93056" }]}><Text style={[styles.resultGlyph, { color: result.won ? "#3DE6E6" : "#D93056" }]}>{result.won ? "✦" : "×"}</Text></View><Eyebrow color={result.won ? "#3DE6E6" : "#D93056"}>Local encounter report</Eyebrow><Text style={styles.resultTitle}>{result.title}</Text><Text style={styles.resultCopy}>{hunterName} returned with a narrative ledger update and cosmetic clearance only. No combat power or real-money reward has been granted.</Text><View style={styles.stats}><Stat value={String(result.score)} label="TARGETS" /><Stat value={String(result.shards)} label="SHARDS" /><Stat value={String(result.shots)} label="SHOTS" /></View>{result.won ? <Panel><Eyebrow color="#E7CB63">Cosmetic record</Eyebrow><Text style={styles.rewardTitle}>“Under the First Eclipse”</Text><Text style={styles.rewardCopy}>A local narrative title has been recorded for this prototype session.</Text></Panel> : <Panel><Eyebrow color="#D93056">Recovery note</Eyebrow><Text style={styles.rewardCopy}>Try a lower pressure level, trigger Veil Step before taking focus fire, and use Shadow Leap to regain vitality.</Text></Panel>}<ActionButton label="REMATCH" onPress={onRematch} /><ActionButton label="CHANGE HUNTER" tone="ghost" onPress={onChange} /></ScrollView></ScreenContainer>; }
function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 32, gap: 15 }, title: { color: "#F5F0E9", fontSize: 29, lineHeight: 34, fontWeight: "900", marginTop: -7 }, lead: { color: "#B9B1C4", fontSize: 13, lineHeight: 19 }, sectionTitle: { color: "#F5F0E9", fontSize: 17, fontWeight: "900" }, hunterGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 2 }, optionWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 2 }, dossier: { borderLeftWidth: 3, marginTop: 3, paddingLeft: 10, gap: 2 }, dossierTitle: { color: "#F5F0E9", fontSize: 16, fontWeight: "900" }, dossierRole: { color: "#A9A3B5", fontSize: 11, fontWeight: "800" }, dossierCopy: { color: "#C7C0D0", fontSize: 12, lineHeight: 17 }, loadout: { fontSize: 9, lineHeight: 14, fontWeight: "900", letterSpacing: 0.35 }, detail: { color: "#B9B1C4", fontSize: 12 }, debrief: { padding: 24, paddingBottom: 32, gap: 15, alignItems: "stretch" }, resultSigil: { width: 85, height: 85, borderWidth: 2, borderRadius: 43, alignSelf: "center", justifyContent: "center", alignItems: "center", backgroundColor: "#17121F" }, resultGlyph: { fontSize: 42, fontWeight: "900" }, resultTitle: { color: "#F5F0E9", fontSize: 28, lineHeight: 33, fontWeight: "900", textAlign: "center" }, resultCopy: { color: "#B9B1C4", fontSize: 13, lineHeight: 19, textAlign: "center" }, stats: { flexDirection: "row", gap: 10 }, stat: { flex: 1, alignItems: "center", paddingVertical: 15, borderRadius: 16, backgroundColor: "#17121F", borderWidth: 1, borderColor: "#30273D" }, statValue: { color: "#F5F0E9", fontSize: 22, fontWeight: "900" }, statLabel: { color: "#A9A3B5", fontSize: 8, fontWeight: "900", letterSpacing: 0.7 }, rewardTitle: { color: "#F5F0E9", fontSize: 17, fontWeight: "900" }, rewardCopy: { color: "#B9B1C4", fontSize: 12, lineHeight: 18 } });
