import { ScrollView, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { useRouter } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { ActionButton, Eyebrow, Panel, Pill, ProgressBar } from "@/components/nf-ui";
import { modeById, multiplayerModes } from "@/lib/multiplayer-modes";
import { useGame } from "@/lib/game-session";

export default function ModesScreen() {
  const router = useRouter() as unknown as { push: (route: string) => void };
  const { width } = useWindowDimensions();
  const wide = width >= 700;
  const { selectedMode, setSelectedMode, prepareMatch } = useGame();
  const mode = modeById(selectedMode);
  const launchLocal = () => { prepareMatch("blood_hunt"); router.push("/hunt"); };
  const modeColor = mode.id === "free_for_all" ? "#D93056" : mode.id === "team_deathmatch" ? "#8E5CFF" : "#3DE6E6";

  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={[styles.content, wide && styles.contentWide]} showsVerticalScrollIndicator={false}>
    <View style={[styles.headerDeck, wide && styles.headerDeckWide]}><View style={styles.headerCopy}><Eyebrow color="#4A877A">Tactical rules board // Local only</Eyebrow><Text style={styles.title}>MODE MATRIX</Text><Text style={styles.lead}>Review the combat rules, select a local doctrine, and deploy an offline simulation. Network play remains disabled until a native transport is actually installed and validated.</Text></View><Panel style={styles.selectorPanel}><Eyebrow color="#C7973A">Choose rule set</Eyebrow><View style={styles.selector}>{multiplayerModes.map((item) => <Pill key={item.id} label={item.shortName} active={selectedMode === item.id} color={item.id === "free_for_all" ? "#D93056" : item.id === "team_deathmatch" ? "#8E5CFF" : "#3DE6E6"} onPress={() => setSelectedMode(item.id)} />)}</View></Panel></View>
    <View style={[styles.board, wide && styles.boardWide]}><Panel style={{ ...styles.modeCard, borderTopColor: modeColor }}><View style={styles.modeHeader}><View><Eyebrow color={modeColor}>Selected doctrine</Eyebrow><Text style={styles.modeTitle}>{mode.name}</Text></View><Text style={[styles.modeCode, { color: modeColor }]}>{mode.shortName}</Text></View><Text style={styles.modeObjective}>{mode.objective}</Text><View style={styles.statRow}><Metric value={mode.teams ? `${mode.teams}` : "—"} label="TEAMS" /><Metric value={`${mode.scoreLimit}`} label={mode.id === "capture_the_flag" ? "CAPTURES" : "SCORE LIMIT"} /><Metric value={`${Math.round(mode.durationSeconds / 60)}m`} label="TIME LIMIT" /></View><Text style={styles.unlock}>{mode.unlock}</Text>{mode.id === "free_for_all" ? <ActionButton label="DEPLOY LOCAL FFA" detail="OFFLINE TARGET SIMULATION" onPress={launchLocal} /> : <ActionButton label="RULES READY — HOST PENDING" detail="NATIVE GODOT VALIDATION REQUIRED" tone="ghost" disabled onPress={() => undefined} />}</Panel>
      <View style={styles.sideStack}><Panel><Eyebrow color="#4A877A">Transport readiness</Eyebrow><Text style={styles.sectionTitle}>COMMAND LINK STATUS</Text><Readiness label="LAN development" value="RULES CONTRACT AVAILABLE" percent={100} color="#3DE6E6" /><Readiness label="Internet P2P" value="DISABLED — NO TRANSPORT" percent={0} color="#D93056" /><Readiness label="Dedicated server" value="PLANNED MIGRATION PATH" percent={10} color="#8E5CFF" /></Panel><Panel><Eyebrow color="#A89D86">Integrity lock</Eyebrow><Text style={styles.adapterCopy}>No credentials, matchmaking, ads, or purchases are silently enabled. These are local rules screens, not a claim that an online service is live.</Text><View style={styles.badges}><Badge label="ADS: OFF" /><Badge label="PURCHASES: OFF" /><Badge label="P2P: OFF" /></View></Panel></View>
    </View>
  </ScrollView></ScreenContainer>;
}

function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Readiness({ label, value, percent, color }: { label: string; value: string; percent: number; color: string }) { return <View style={styles.readiness}><View style={styles.readinessHeader}><Text style={styles.readinessLabel}>{label}</Text><Text style={[styles.readinessValue, { color }]}>{value}</Text></View><ProgressBar value={percent} color={color} /></View>; }
function Badge({ label }: { label: string }) { return <View style={styles.badge}><Text style={styles.badgeText}>{label}</Text></View>; }

const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 28, gap: 13 }, contentWide: { paddingHorizontal: 24, paddingTop: 14, maxWidth: 1440, alignSelf: "center", width: "100%" }, headerDeck: { gap: 11 }, headerDeckWide: { flexDirection: "row", alignItems: "stretch" }, headerCopy: { flex: 1, gap: 4 }, title: { color: "#EDE1C4", fontSize: 30, lineHeight: 35, fontWeight: "900", letterSpacing: 0.8 }, lead: { color: "#B9AF9A", fontSize: 12, lineHeight: 18, maxWidth: 700 }, selectorPanel: { minWidth: 320, justifyContent: "center", borderLeftWidth: 3, borderLeftColor: "#C7973A" }, selector: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, board: { gap: 12 }, boardWide: { flexDirection: "row", alignItems: "stretch" }, modeCard: { flex: 1.25, gap: 14, borderTopWidth: 3 }, sideStack: { flex: 0.9, gap: 12 }, modeHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, modeTitle: { color: "#EDE1C4", fontSize: 26, lineHeight: 31, fontWeight: "900", marginTop: 2 }, modeCode: { fontSize: 27, fontWeight: "900", letterSpacing: 1 }, modeObjective: { color: "#D2C6B3", fontSize: 13, lineHeight: 19 }, statRow: { flexDirection: "row", gap: 9 }, metric: { flex: 1, paddingVertical: 11, alignItems: "center", borderRadius: 10, backgroundColor: "#211A15", borderWidth: 1, borderColor: "#443423" }, metricValue: { color: "#F5F0E9", fontSize: 20, fontWeight: "900" }, metricLabel: { color: "#A89D86", fontSize: 8, fontWeight: "900", letterSpacing: 0.6, marginTop: 2 }, unlock: { color: "#E7CB63", fontSize: 10, lineHeight: 15, fontWeight: "800" }, sectionTitle: { color: "#EDE1C4", fontSize: 15, fontWeight: "900" }, readiness: { gap: 5, marginTop: 4 }, readinessHeader: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, readinessLabel: { color: "#D7C9B5", fontSize: 11, fontWeight: "800" }, readinessValue: { flex: 1, textAlign: "right", fontSize: 8, fontWeight: "900", letterSpacing: 0.4 }, adapterCopy: { color: "#B9AF9A", fontSize: 11, lineHeight: 16 }, badges: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, badge: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 99, backgroundColor: "#211A15", borderWidth: 1, borderColor: "#493C28" }, badgeText: { color: "#CFC2AB", fontSize: 8, fontWeight: "900", letterSpacing: 0.5 } });
